const i18n = {
    'en' : {
        'skills': 'Skills',
        'portfolio': 'Portfolio',
        'video': 'Video',
        'price': 'Price',
        'contacts': 'Contacts',
        'hero-title': 'Alexa Rise',
        'hero-subtitle': 'Save sincere emotions, romantic feelings and happy moments of life together with professional photographer Alexa Rise',
        'hero-button': 'Hire me',
        'skill-title-1': 'Digital photography',
        'skill-subtitle-1': 'High-quality photos in the studio and on the nature',
        'skill-title-2': 'Video shooting',
        'skill-subtitle-2': 'Capture your moments so that they always stay with you',
        'skill-title-3': 'Retouch',
        'skill-subtitle-3': 'I strive to make photography surpass reality',
        'skill-title-4': 'Audio',
        'skill-subtitle-4': 'Professional sounds recording for video, advertising, portfolio',
        'portfolio-button-winter': 'Winter',
        'portfolio-button-spring': 'Spring',
        'portfolio-button-summer': 'Summer',
        'portfolio-button-autumn': 'Autumn',
        'price-card-1-title': 'Standard',
        'price-card-1-subtitle1': 'One location',
        'price-card-1-subtitle2': '120 photos in color',
        'price-card-1-subtitle3': '12 photos in retouch',
        'price-card-1-subtitle4': 'Readiness 2-3 weeks',
        'price-card-1-subtitle5': 'Make up, visage',
        'price-card-2-title': 'Premium',
        'price-card-2-subtitle1': 'One or two locations',
        'price-card-2-subtitle2': '200 photos in color',
        'price-card-2-subtitle3': '20 photos in retouch',
        'price-card-2-subtitle4': 'Readiness 1-2 weeks',
        'price-card-2-subtitle5': 'Make up, visage',
        'price-card-3-title': 'Gold',
        'price-card-3-subtitle1': 'Three locations or more',
        'price-card-3-subtitle2': '300 photos in color',
        'price-card-3-subtitle3': '50 photos in retouch',
        'price-card-3-subtitle4': 'Readiness 1 week',
        'price-card-3-subtitle5': 'Make up, visage, hairstyle',
        'price-button': 'Order shooting',
        'contact-me': 'Contact me',
        'button-send-message': 'Send message'
    },
    'ru' : {
        'skills': 'Навыки',
        'portfolio': 'Портфолио',
        'video': 'Видео',
        'price': 'Цены',
        'contacts': 'Контакты',
        'hero-title': 'Алекса Райс',
        'hero-subtitle': 'Сохраните искренние эмоции, романтические переживания и счастливые моменты жизни вместе с профессиональным фотографом',
        'hero-button': 'Пригласить',
        'skill-title-1': 'Фотография',
        'skill-subtitle-1': 'Высококачественные фото в студии и на природе',
        'skill-title-2': 'Видеосъемка',
        'skill-subtitle-2': 'Запечатлите лучшие моменты, чтобы они всегда оставались с вами',
        'skill-title-3': 'Ретушь',
        'skill-subtitle-3': 'Я стремлюсь к тому, чтобы фотография превосходила реальность',
        'skill-title-4': 'Звук',
        'skill-subtitle-4': 'Профессиональная запись звука для видео, рекламы, портфолио',
        'portfolio-button-winter': 'Зима',
        'portfolio-button-spring': 'Весна',
        'portfolio-button-summer': 'Лето',
        'portfolio-button-autumn': 'Осень',
        'price-card-1-title': 'Стандарт',
        'price-card-1-subtitle1': 'Одна локация',
        'price-card-1-subtitle2': '120 цветных фото',
        'price-card-1-subtitle3': '12 отретушированных фото',
        'price-card-1-subtitle4': 'Готовность через 2-3 недели',
        'price-card-1-subtitle5': 'Макияж, визаж',
        'price-card-2-title': 'Премиум',
        'price-card-2-subtitle1': 'Одна-две локации',
        'price-card-2-subtitle2': '200 цветных фото',
        'price-card-2-subtitle3': '20 отретушированных фото',
        'price-card-2-subtitle4': 'Готовность через 1-2 недели',
        'price-card-2-subtitle5': 'Макияж, визаж',
        'price-card-3-title': 'Голд',
        'price-card-3-subtitle1': 'Три локации и больше',
        'price-card-3-subtitle2': '300 цветных фото',
        'price-card-3-subtitle3': '50 отретушированных фото',
        'price-card-3-subtitle4': 'Готовность через 1 неделю',
        'price-card-3-subtitle5': 'Макияж, визаж, прическа',
        'price-button': 'Заказать съемку',
        'contact-me': 'Свяжитесь со мной',
        'button-send-message': 'Отправить'
    }
};

export default i18n;